apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example 
  
---
 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx-example
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
 
---
 
apiVersion: v1
kind: Pod
metadata:
  namespace: nginx-example
  name: nginx
  labels:
    app: nginx
    environment: nginx-example
spec:
  containers:
  - image: nginx:1.7.9
    name: nginx
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: volume
    ports:
    - containerPort: 80
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: nginx-pvc  
  
---
 
kind: Service
apiVersion: v1
metadata:
  name:  nginx
  namespace: nginx-example
spec:
  selector:
    app: nginx
    environment: nginx-example
  type:  LoadBalancer
  ports:
  - port:  80
    targetPort:  80