apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-v1
  labels:
    app: sample-app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-v1
  template:
    metadata:
      labels:
        app: sample-app-v1
    spec:
      containers:
      - name: sample-app-v1
        image: democncfarchacr.azurecr.io/nginx:1.7.9
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: democncfarch-acr-sec